### ISSUE TITLE
Publish native ES6 module

### ISSUE THREAD

**Issue by dandv** [Preposterous/twitter-lite#3]
Would go along great with the modern foundations of this library.

[Babel is dead! How to publish native ES modules backwards compatible with Node < 8.5.0](https://medium.com/@dandv/publishing-native-es-modules-with-node-v8-5-0-730736e0f612)

**Comment by peterpme** [comment]
Hey @dandv!

Would love to but will there be any backward compatibility issues?

**Comment by dandv** [comment]
(updated my OP to specify that the Medium post offers a solution to publish native ES6 modules with backwards compatibility for Node < 8.5.0)

I haven't been made aware of any compatibility issue via the Medium post, or via this package I've published - [local-iso-dt](https://www.npmjs.com/package/local-iso-dt) has been out for a while and haven't had any complaints, but arguably it's less popular than twitter-lite can be :)

Before v1 would be a great time to go ES6 and see if anyone reports any compat issues.

**Comment by tylerbuchea** [comment]
Just opened a PR for this #20

**Comment by tylerbuchea** [comment]
I'm actually having second thoughts on this PR. One thing Microbundle gives us besides bundling is ESNext support, which is nice and looking into the future there will probably always be certain features we want to use that aren't supported right away.

I'm open for debate though. Otherwise I think we can close this issue.

**Comment by peterpme** [comment]
Closing!
