### ISSUE TITLE
Direct messages.

### ISSUE THREAD

**Issue by neeeeds** [Preposterous/twitter-lite#30]
Hi, can you post an example on how to post a DM ? 
thank you.

**Comment by dandv** [comment]
Hey! Turns out we weren't stringifying nested objects, so I've just fixed that in 6ae2f99c35eda2b8d58ef5b68fe6f0017d8a9cb0

@peterpme, can you please `npm publish`?

@neeeeds: In the meantime, if you install the package from this repo, how does [this](https://github.com/Preposterous/twitter-lite/blob/master/twitter.test.js#L151) work for you?

**Comment by neeeeds** [comment]
it executes, but it does not post a new message. checked the keys and secrets, everything is ok but it does not work.

**Comment by dandv** [comment]
What's in the `response` object?

**Comment by neeeeds** [comment]
nothing.
it executes and then nothing.

**Comment by neeeeds** [comment]
now i get it is not defined.

**Comment by neeeeds** [comment]
![screenshot](https://user-images.githubusercontent.com/9222035/42661601-fc9dd366-862e-11e8-8739-210d4858ddf9.png)

**Comment by dandv** [comment]
Looks like Twitter had a transient auth error. All tests pass now, including sending DMs, and I've verified the DMs were received.

**Comment by neeeeds** [comment]
![token](https://user-images.githubusercontent.com/9222035/42718972-502fab2c-870f-11e8-868e-4cc1092e6491.png)
And now i am having this error
any idead why ? thank you very much.

**Comment by dandv** [comment]
Tests should be run with Jest rather than mocha (`npm run test`), but some will fail on your machine because you don't have the test account's credentials (@nodejs_lite).

I pointed at the test to help you copy/paste code to send DMs. Can you try [that](https://github.com/Preposterous/twitter-lite/blob/master/twitter.test.js#L149-L167) in a standalone script, replace the recipient_id with the id of the user you want to DM (get it from http://gettwitterid.com), then `console.log(response)`?

**Comment by neeeeds** [comment]
hi mate, i tested it with the new example and it workded very well, thank you for this great job.
